From 68e246501f39dc5d97f62fab13c075168ab9d9fe Mon Sep 17 00:00:00 2001
From: mudler <mudler@sabayon.org>
Date: Sun, 16 Oct 2016 20:22:06 +0200
Subject: [PATCH] pyanaconda/nm: nm_device_setting_value returns None if no
 path could be found

---
 pyanaconda/nm.py | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/pyanaconda/nm.py b/pyanaconda/nm.py
index c8e0813..4d16233 100644
--- a/pyanaconda/nm.py
+++ b/pyanaconda/nm.py
@@ -746,7 +746,8 @@ def nm_device_setting_value(name, key1, key2):
     """
     settings_paths = _device_settings(name)
     if not settings_paths:
-        raise SettingsNotFoundError(name)
+        value = None
+        return value
     else:
         settings_path = settings_paths[0]
     proxy = _get_proxy(object_path=settings_path, interface_name="org.freedesktop.NetworkManager.Settings.Connection")
-- 
2.10.0

